---
- name: Update APT repo information
  apt: update-cache=yes

- name: remove /sbin/start
  file: path=/sbin/start state=absent
  when: ansible_distribution_major_version <= "14"

- name: Copy in fake /sbin/start to fool upstart
  copy: src=sbin/start dest=/sbin/start owner=root mode=744
  when: ansible_distribution_major_version <= "14"

- name: Install enhanced networking kernel
  apt: pkg=linux-aws state=latest
  when: ansible_distribution_major_version >= "16"

- name: Install packages
  apt: pkg={{ item }} state=latest
  with_items:
    #- ca-certificates-java
    - curl
    - dnsutils
    - git
    - htop
    - jq
    - less
    - linux-tools-common
    - linux-tools-generic
    - linux-cloud-tools-generic
    - lynx
    - make
    - mdadm
    - nano
    - ngrep
    - nmon
    - ntp
    - perl
    - perl-modules
    - python
    - python-pip
    - rsync
    - runit
    - ssh
    - sudo
    - sysstat
    - tcpdump
    - telnet
    - traceroute
    - unzip
    - vim
    - xfsprogs
    - zip

- name: install python-support
  apt: pkg=python-support state=latest
  when: ansible_distribution_major_version <= "14"

- name: remove /sbin/start again
  file: path=/sbin/start state=absent
  when: ansible_distribution_major_version <= "14"

- name: relink /sbin/start
  file: src=/sbin/initctl dest=/sbin/start owner=root state=link
  when: ansible_distribution_major_version <= "14"

