---

- name: Make sure rsync is not running as a service
  command: update-rc.d rsync disable
  when: ansible_distribution == 'Ubuntu'
  
- name: Enable NTP service
  command: update-rc.d ntp enable

- name: Starting NTP
  command: service ntp start
  when: not image_build

- name: Stopping NTP
  command: service ntp stop
  when: image_build
  
- name: Add motd additions
  template: src=motd-20-sysinfo dest=/etc/update-motd.d/20-sysinfo mode=0755 owner=root
  when: cloud_target == "amazon"

